# Generated by Django 4.2.21 on 2025-05-27 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstruccionEmbarque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puerto_carga', models.CharField(max_length=100, verbose_name='Puerto de Carga (POL)')),
                ('puerto_descarga', models.CharField(max_length=100, verbose_name='Puerto de Descarga (POD)')),
                ('fecha_embarque_estimada', models.DateField(verbose_name='Fecha de Embarque Estimada')),
                ('descripcion_mercancia', models.TextField(verbose_name='Descripcion de la Mercancia')),
                ('cantidad_bultos', models.IntegerField(verbose_name='Cantidad de Bultos')),
                ('peso_bruto_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Bruto (KG)')),
                ('volumen_cbm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volumen (CBM)')),
                ('numero_contenedor', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero de Contenedor')),
                ('numero_sello', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero de Sello')),
                ('tipo_servicio', models.CharField(choices=[('FCL', 'Full Container Load'), ('LCL', 'Less than Container Load')], max_length=50, verbose_name='Tipo de Servicio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrucciones_como_consignee', to='app.cliente', verbose_name='Consignatario')),
                ('notify_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrucciones_como_notify_party', to='app.cliente', verbose_name='Parte a Notificar')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrucciones_como_shipper', to='app.cliente', verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Instruccion de Embarque',
                'verbose_name_plural': 'Instrucciones de Embarque',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
