# Generated by Django 5.2.1 on 2025-05-27 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaCarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa_solicitante', models.CharField(max_length=255, verbose_name='Nombre Empresa Solicitante / Contacto')),
                ('id_cliente_texto', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Cliente (Texto ingresado)')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('telefono_contacto', models.CharField(max_length=30, verbose_name='Teléfono de Contacto')),
                ('numero_cotizacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Cotización')),
                ('descripcion_mercancia', models.TextField(verbose_name='Descripción de la Mercancía')),
                ('tipo_mercancia', models.CharField(choices=[('general', 'General'), ('peligrosa', 'Peligrosa IMO Class'), ('refrigerada', 'Refrigerada'), ('perecedera', 'Perecedera'), ('sobredimensionada', 'Sobredimensionada'), ('otros', 'Otros')], default='general', max_length=50, verbose_name='Tipo de Mercancía')),
                ('peso_bruto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Peso Bruto Total')),
                ('unidad_peso', models.CharField(choices=[('KG', 'KG'), ('TON', 'Toneladas'), ('LBS', 'Libras')], default='KG', max_length=3, verbose_name='Unidad de Peso')),
                ('volumen_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volumen Total (CBM)')),
                ('numero_bultos', models.IntegerField(verbose_name='Número de Bultos/Paquetes')),
                ('codigo_hs', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código HS')),
                ('tipo_contenedor', models.CharField(choices=[('20GP', "20' de uso general"), ('40GP', "40' de uso general"), ('40HC', 'Cubo alto de uso general de 40 pies'), ('refrigerado', 'Contenedor frigorífico')], max_length=50, verbose_name='Tipo de Contenedor')),
                ('cantidad_contenedores', models.IntegerField(verbose_name='Cantidad de Contenedores')),
                ('condiciones_especiales_contenedor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Condiciones Especiales del Contenedor')),
                ('puerto_origen', models.CharField(max_length=100, verbose_name='Puerto de Origen (POL)')),
                ('puerto_destino', models.CharField(max_length=100, verbose_name='Puerto de Destino (POD)')),
                ('puerto_transbordo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Puerto de Transbordo')),
                ('fecha_embarque', models.DateField(verbose_name='Fecha Estimada de Embarque (ETD)')),
                ('fecha_limite_llegada', models.DateField(blank=True, null=True, verbose_name='Fecha Límite de Llegada')),
                ('viaje_buque', models.CharField(blank=True, max_length=100, null=True, verbose_name='Selección de Viaje/Buque Específico')),
                ('shipper_nombre', models.CharField(max_length=255, verbose_name='Shipper: Nombre Completo / Razón Social')),
                ('shipper_direccion', models.TextField(verbose_name='Shipper: Dirección Completa')),
                ('shipper_telefono', models.CharField(max_length=30, verbose_name='Shipper: Teléfono de Contacto')),
                ('shipper_email', models.EmailField(max_length=254, verbose_name='Shipper: Email de Contacto')),
                ('consignee_nombre', models.CharField(max_length=255, verbose_name='Consignee: Nombre Completo / Razón Social')),
                ('consignee_direccion', models.TextField(verbose_name='Consignee: Dirección Completa')),
                ('consignee_telefono', models.CharField(max_length=30, verbose_name='Consignee: Teléfono de Contacto')),
                ('consignee_email', models.EmailField(max_length=254, verbose_name='Consignee: Email de Contacto')),
                ('notify_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notify Party: Nombre Completo / Razón Social')),
                ('notify_direccion', models.TextField(blank=True, null=True, verbose_name='Notify Party: Dirección Completa')),
                ('notify_telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Notify Party: Teléfono de Contacto')),
                ('notify_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Notify Party: Email de Contacto')),
                ('seguro_carga', models.BooleanField(default=False, verbose_name='Seguro de Carga')),
                ('despacho_origen', models.BooleanField(default=False, verbose_name='Despacho Aduanal en Origen')),
                ('despacho_destino', models.BooleanField(default=False, verbose_name='Despacho Aduanal en Destino')),
                ('transporte_origen', models.BooleanField(default=False, verbose_name='Transporte Terrestre en Origen (Pre-carriage)')),
                ('transporte_destino', models.BooleanField(default=False, verbose_name='Transporte Terrestre en Destino (On-carriage)')),
                ('otros_servicios', models.CharField(blank=True, max_length=255, null=True, verbose_name='Otros Servicios (Especificar)')),
                ('instrucciones_especiales', models.TextField(blank=True, null=True, verbose_name='Instrucciones Especiales / Comentarios')),
                ('temperatura_requerida', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Temperatura Requerida')),
                ('unidad_temperatura', models.CharField(blank=True, choices=[('C', '°C'), ('F', '°F')], max_length=1, null=True, verbose_name='Unidad de Temperatura')),
                ('ventilacion_requerida', models.BooleanField(default=False, verbose_name='Ventilación Requerida')),
                ('numero_un', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número UN')),
                ('imo_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='IMO Class')),
                ('packing_group', models.CharField(blank=True, max_length=50, null=True, verbose_name='Packing Group')),
                ('notas_documentacion', models.TextField(blank=True, null=True, verbose_name='Notas sobre Documentación')),
                ('fecha_creacion_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación de Reserva')),
                ('ultima_actualizacion_reserva', models.DateTimeField(auto_now=True, verbose_name='Última Actualización de Reserva')),
                ('estado_reserva', models.CharField(choices=[('solicitada', 'Solicitada'), ('confirmada', 'Confirmada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=20, verbose_name='Estado de la Reserva')),
                ('id_cliente_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente', verbose_name='Cliente Asociado (Opcional)')),
            ],
            options={
                'verbose_name': 'Reserva de Carga',
                'verbose_name_plural': 'Reservas de Carga',
                'ordering': ['-fecha_creacion_reserva'],
            },
        ),
    ]
