# Generated by Django 5.2.1 on 2025-05-29 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reservacarga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10, verbose_name='Código del país')),
                ('phone', models.CharField(max_length=30, verbose_name='Número de teléfono')),
                ('company', models.CharField(max_length=255, verbose_name='Nombre de empresa')),
                ('tax_id', models.CharField(max_length=100, verbose_name='Impuesto de Sociedades / Registro / Número de IVA')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección de la calle / Número')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Código postal')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
