# Generated by Django 5.2.1 on 2025-06-06 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacarga',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='country',
            field=models.CharField(choices=[('España', 'España'), ('México', 'México'), ('Colombia', 'Colombia'), ('Estados Unidos', 'Estados Unidos')], max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='country_code',
            field=models.CharField(choices=[('+34', '+34 España'), ('+52', '+52 México'), ('+57', '+57 Colombia'), ('+1', '+1 USA')], max_length=10, verbose_name='Código del país'),
        ),
    ]
