# Generated by Django 4.2.21 on 2025-06-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='country',
            field=models.CharField(choices=[('España', 'España'), ('México', 'México'), ('Colombia', 'Colombia'), ('Estados Unidos', 'Estados Unidos')], max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='country_code',
            field=models.CharField(choices=[('+34', '+34 España'), ('+52', '+52 México'), ('+57', '+57 Colombia'), ('+1', '+1 USA')], max_length=10, verbose_name='Código del país'),
        ),
    ]
