# Generated by Django 4.2.21 on 2025-06-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_perfilusuario_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfLadingDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.CharField(max_length=20)),
                ('container', models.CharField(max_length=20)),
                ('consignee', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending Review', 'Pending Review'), ('Requires Changes', 'Requires Changes'), ('Approved', 'Approved')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rejection_comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='instruccionembarque',
            options={},
        ),
        migrations.RemoveField(
            model_name='instruccionembarque',
            name='cantidad_bultos',
        ),
        migrations.RemoveField(
            model_name='instruccionembarque',
            name='consignee',
        ),
        migrations.RemoveField(
            model_name='instruccionembarque',
            name='descripcion_mercancia',
        ),
        migrations.RemoveField(
            model_name='instruccionembarque',
            name='fecha_embarque_estimada',
        ),
        migrations.RemoveField(
            model_name='instruccionembarque',
            name='notify_party',
        ),
        migrations.RemoveField(
            model_name='instruccionembarque',
            name='numero_sello',
        ),
        migrations.RemoveField(
            model_name='instruccionembarque',
            name='peso_bruto_kg',
        ),
        migrations.RemoveField(
            model_name='instruccionembarque',
            name='puerto_carga',
        ),
        migrations.RemoveField(
            model_name='instruccionembarque',
            name='puerto_descarga',
        ),
        migrations.RemoveField(
            model_name='instruccionembarque',
            name='shipper',
        ),
        migrations.RemoveField(
            model_name='instruccionembarque',
            name='tipo_servicio',
        ),
        migrations.RemoveField(
            model_name='instruccionembarque',
            name='ultima_actualizacion',
        ),
        migrations.RemoveField(
            model_name='instruccionembarque',
            name='volumen_cbm',
        ),
        migrations.AddField(
            model_name='instruccionembarque',
            name='consignatario',
            field=models.TextField(blank=True, null=True, verbose_name='Consignatario'),
        ),
        migrations.AddField(
            model_name='instruccionembarque',
            name='descripcion_carga',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la Carga'),
        ),
        migrations.AddField(
            model_name='instruccionembarque',
            name='estado',
            field=models.CharField(default='Pendiente de Revisión', max_length=50, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='instruccionembarque',
            name='exportador',
            field=models.TextField(blank=True, null=True, verbose_name='Exportador'),
        ),
        migrations.AddField(
            model_name='instruccionembarque',
            name='instrucciones_especiales',
            field=models.TextField(blank=True, null=True, verbose_name='Instrucciones Especiales'),
        ),
        migrations.AddField(
            model_name='instruccionembarque',
            name='notificar_a',
            field=models.TextField(blank=True, null=True, verbose_name='Notificar a'),
        ),
        migrations.AddField(
            model_name='instruccionembarque',
            name='numero_booking',
            field=models.CharField(default='sin booking', max_length=50, verbose_name='Número de Booking'),
        ),
        migrations.AddField(
            model_name='instruccionembarque',
            name='puerto_destino',
            field=models.CharField(default='sin puerto', max_length=100, verbose_name='Puerto de Destino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instruccionembarque',
            name='puerto_embarque',
            field=models.CharField(default='sin puerto', max_length=100, verbose_name='Puerto de Destino'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instruccionembarque',
            name='numero_contenedor',
            field=models.CharField(max_length=50, null=True, verbose_name='Número de Contenedor'),
        ),
    ]
