# Generated by Django 5.2.1 on 2025-06-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_perfilusuario_country_and_more'),
        ('app', '0005_billofladingdraft_alter_instruccionembarque_options_and_more'),
    ]

    operations = [
    ]
