# Generated by Django 5.0.4 on 2025-06-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20250608_1321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillOfLadingDraft',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='country',
        ),
        migrations.AlterField(
            model_name='instruccionembarque',
            name='puerto_destino',
            field=models.CharField(default='sin puertp', max_length=100, verbose_name='Puerto de Destino'),
        ),
        migrations.AlterField(
            model_name='instruccionembarque',
            name='puerto_embarque',
            field=models.CharField(max_length=100, null=True, verbose_name='Puerto de Destino'),
        ),
    ]
