# Generated by Django 5.2.1 on 2025-06-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_billofladingdraft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruccionembarque',
            name='bl_pdf',
            field=models.FileField(blank=True, null=True, upload_to='bill_of_lading/'),
        ),
    ]
