# Generated by Django 5.2.1 on 2025-06-11 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_instruccionembarque_bl_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruccionembarque',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.reservacarga', verbose_name='Reserva Relacionada'),
        ),
    ]
