# Generated by Django 5.2.1 on 2025-06-11 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_instruccionembarque_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruccionembarque',
            name='reserva',
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puerto', models.CharField(max_length=100, verbose_name='Puerto')),
                ('tipo', models.CharField(choices=[('factura', 'Factura de Desembarco'), ('manifiesto', 'Manifiesto'), ('certificado', 'Certificado de Origen'), ('otros', 'Otros')], max_length=20, verbose_name='Tipo de Documento')),
                ('archivo', models.FileField(upload_to='documentos_pdf/', verbose_name='Archivo PDF')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10, verbose_name='Estado de Validación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('embarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.instruccionembarque')),
            ],
        ),
    ]
