# Generated by Django 5.2.1 on 2025-06-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_instruccionembarque_reserva_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='puerto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Puerto asignado'),
        ),
    ]
