# Generated by Django 5.2.1 on 2025-06-11 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_perfilusuario_puerto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Puerto')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
            ],
        ),
        migrations.RemoveField(
            model_name='documento',
            name='puerto',
        ),
        migrations.AddField(
            model_name='documento',
            name='es_obligatorio',
            field=models.BooleanField(default=True, verbose_name='Es Obligatorio'),
        ),
        migrations.AddField(
            model_name='documento',
            name='es_original',
            field=models.BooleanField(default=True, verbose_name='Es Original'),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Emisión'),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Validación'),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='numero_referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Referencia'),
        ),
        migrations.AddField(
            model_name='documento',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('validado', 'Validado'), ('rechazado', 'Rechazado'), ('requiere_correccion', 'Requiere Corrección')], default='pendiente', max_length=20, verbose_name='Estado de Validación'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('factura', 'Factura de Desembarco'), ('manifiesto', 'Manifiesto de Carga'), ('certificado_origen', 'Certificado de Origen'), ('certificado_sanitario', 'Certificado Sanitario/Fitosanitario'), ('packing_list', 'Packing List'), ('conocimiento_embarque', 'Conocimiento de Embarque'), ('declaracion_aduanera', 'Declaración Aduanera'), ('permiso_importacion', 'Permiso de Importación'), ('otros', 'Otros')], max_length=30, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='instruccionembarque',
            name='puerto_destino',
            field=models.CharField(default='sin puerto', max_length=100, verbose_name='Puerto de Destino'),
        ),
        migrations.AlterField(
            model_name='instruccionembarque',
            name='puerto_embarque',
            field=models.CharField(max_length=100, null=True, verbose_name='Puerto de Embarque'),
        ),
        migrations.AddField(
            model_name='documento',
            name='puerto_objeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='app.puerto'),
        ),
    ]
