# Generated by Django 5.2.1 on 2025-06-11 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_puerto_remove_documento_puerto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruccionembarque',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrucciones', to='app.reservacarga'),
        ),
        migrations.AlterField(
            model_name='instruccionembarque',
            name='numero_booking',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Booking'),
        ),
        migrations.AlterField(
            model_name='instruccionembarque',
            name='puerto_destino',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Puerto de Destino'),
        ),
    ]
