# Generated by Django 5.2.1 on 2025-06-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_instruccionembarque_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='', verbose_name='Archivo PDF'),
        ),
    ]
